In [1]:
import numpy as np

mat_a=np.matrix([0,3,5,5,5,2]).reshape(2,3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [4]:
mat_b=np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [5]:
mat_a*mat_b

matrix([[ 29, -16],
        [ 38,   6]])

In [6]:
product=np.matmul(mat_a,mat_b)
product

matrix([[ 29, -16],
        [ 38,   6]])

In [ ]:
# All the above operations can be also performed on numpy arrays
# Just replace all np.matrix with np.array