In [3]:
#Using normal python code
list_two=list(range(1,4))
list_three=list(range(1,4))
list_sum=[]

for index in range(3):
    list_two[index]=list_two[index]**2
    list_three[index]=list_three[index]**3
    
    list_sum.append(list_two[index]+list_three[index])
print(list_sum)

[2, 12, 36]


In [6]:
#Using numpy 
import numpy as np

array_two=np.arange(1,4)**2
print(array_two)

[1 4 9]


In [7]:
array_three=np.arange(1,4)**3
print(array_three)

[ 1  8 27]


In [8]:
print(array_two+array_three)

[ 2 12 36]


In [10]:
print(np.power(np.array([1,2,3]),4))

[ 1 16 81]


In [11]:
print(np.array([1,2,3])**2)

[1 4 9]


In [14]:
print(np.exp(np.negative(np.array([1,2,3]))))

[0.36787944 0.13533528 0.04978707]


In [15]:
#Sample array
sample_array=np.array([1,2,3])

In [16]:
print(np.sin(sample_array))

[0.84147098 0.90929743 0.14112001]


In [17]:
#Note: All the above mentioned functions are element by element operations