In [1]:
import numpy as np

x=np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [2]:
#Take from 3 to 7
print(x[2:7])

#The end index is exclusive
#The start index in inclusive

[3 4 5 6 7]


In [3]:
#Slicing with a step size
print(x[2:7:2])

[3 5 7]


In [4]:
print(x[:7])

[1 2 3 4 5 6 7]


In [5]:
print(x[2:])

[3 4 5 6 7 8 9]
