In [4]:
import numpy as np

x=np.arange(18)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [6]:
#Reshape into a 2D Array
print(x.reshape(3,3,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
